public class veiculo {
    public String tipo = 'marca não definida';
    public String marca = 'marca não definida';
    public String modelo = 'modelo não definido';
    public String proprietario = 'dono não definido';
    public Decimal valorDeCompra = 0;
    public Decimal valorDeVenda = 0;
    public Integer anoDeLancamento = 0;
    public Integer desvalorizacao = 200;
    
    
    public void mudarProprietario (String novoDono){
    proprietario = novoDono;
    }
    
    
 

    }